### ISSUE TITLE
Setting auth.params.device inside lock.show() doesn't work

### ISSUE THREAD

**Issue by Lknechtli** [auth0/angular-lock#13]
In my application, we intend to allow users to create refresh tokens for direct api interaction.
The workflow to create a refresh token involves calling

``` javascript
lock.show({
  auth: {
    params: {
      scope: 'openid offline_access',
      device: someVar
    }
  }
});
```

When we then list the user's active refresh tokens, the objects returned from the auth0 API all have the `device_name` attribute set to `Browser`, instead of the contents of `someVar`.  It seems like `auth.params.device` is being overwritten at some point.

**Comment by chenkie** [comment]
Can you confirm that you're using Lock 10? Options should be registered in `$lockProvider.init` instead of the `show` method.

```js
$lockProvider.init({
  clientID: AUTH0_CLIENT_ID,
  domain: AUTH0_DOMAIN,
  options: {
    ...
  }
});
```

**Comment by Lknechtli** [comment]
I am using `auth0-lock: "^10.4.0"`. I have my general login options set in `$lockProvider.init`, but in this case I'm showing a second login prompt that's different from the initial login in order to retrieve the refresh token.

According to your documentation here: https://auth0.com/docs/libraries/lock/v10/api#show-options- and here: https://auth0.com/docs/libraries/lock/v10/sending-authentication-parameters
the `lock.show()` function does take some parameters:
```
The following subset of options to be overridden from the values they were given (or their defaults) when Lock was instantiated:

allowedConnections
auth.params
allowLogin
allowSignUp
allowForgotPassword
initialScreen
rememberLastLogin
```

**Comment by Lknechtli** [comment]
In either case, setting the `auth.params.device` in `$lockProvider.init` doesn't work either.

**Comment by chenkie** [comment]
We've got a patch in for this, should be fixed up on the next release of auth0.js.

**Comment by moravcik** [comment]
For me getting a refreshToken works with this:  

    lock.show({
      auth: {
        params: {
          scope: 'openid offline_access'
        }
      }
    }
