### ISSUE TITLE
Input values are not cleared

### ISSUE THREAD

**Issue by ozooner** [auth0/angular-lock#17]
Hi,

This issue is specific to popup mode login, as there is no redirection, the auth0 lock instance will remain in browser memory. Due to that nuance, when user logs out, and opens the log-in window again (rememberLastLogin disabled), the input fields in the lock remain from previous login.
I decided that angular-lock would be more fitting repo for this issue, as with the original lock I could create new instance of the lock every time the button is pressed, however with angular, there is only single lock instance created with app initialization.
Video explains better: [https://youtu.be/frPcOG40C-s](https://youtu.be/frPcOG40C-s)

Regards,
ozooner

**Comment by chenkie** [comment]
Are you needing to create a new instance for any other reason than just to clear the input fields? If not, I think we should look at a different approach/fix. Creating a new instance every time seems unnecessary.

**Comment by ozooner** [comment]
No, ideally the lock would clear the input values once authentication is successful.
I was just implying that creating new lock instance would be a 'quick fix' if I was using the plain lock file, however since angular-lock only creates one instance of lock, I can't even do that...

**Comment by chenkie** [comment]
I've submitted an issue for this in the Lock repo: https://github.com/auth0/lock/issues/795

Stay tuned there for a change there.
