### ISSUE TITLE
Incompatible with Lock 10.9.0 (Auth0.js v8)

### ISSUE THREAD

**Issue by ronalders** [auth0/angular-lock#18]
Since Lock 10.9.0 Auth0 v8 is used. And angular-lock is still depending on auth0.js v7 in the interceptHash function. The init of Auth0(credentials) no longer exists within Auth0.js v8. 

```
lock.interceptHash = function() {
        $rootScope.$on('$locationChangeStart', function(event, location) {

          if (/id_token=/.test(location) || /error=/.test(location)) {
            var auth0 = new Auth0(credentials);
```

**Comment by chenkie** [comment]
You can use 2.0.0-beta.0 with Lock 10.9 :) https://github.com/auth0/angular-lock/tree/v2

I'll update the main readme to reflect this.
