### ISSUE TITLE
lock.show is not overriding set properties (prefill)

### ISSUE THREAD

**Issue by ajones-miovision** [auth0/angular-lock#19]
I'm having trouble setting the 'prefill' value in lock.show. I set up an initial value in the lock initialization and then I attempt to override the value on lock.show. According to the [documentation](https://auth0.com/docs/libraries/lock/v10/api#show-), options provided in lock.show should override options set during initialization.

in lockProvider.init I have:
```
prefill: {
    email: 'test@test.com'
}
```

and in lock.show i override this value
```
prefill: {
    email: 'signup@test.com
}
```

but the page always loads with the initial email set.

**Comment by ajones-miovision** [comment]
Sorry, i just realized that prefill is not overridable

**Comment by bosticka** [comment]
But why? I have a use case where I want to set the email address from query string values from redirect URLs in the email templates, e.g. A welcome email with a link inside to lock widget with initial page forgotPassword and the users email already filled in so they only have to click Send Email....
