### ISSUE TITLE
It tries to fetch some weird file.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [auth0/angular-lock#20]
So it uses clientID as a reference for some js file.

![screen shot 2017-01-18 at 13 47 38](https://cloud.githubusercontent.com/assets/4464561/22061147/be114b2c-dd84-11e6-870c-33bba6764919.png)

**Comment by chenkie** [comment]
That call should be going to `cdn.auth0.com/client/...`

Which version of Lock are you using? Can you post your configuration?

**Comment by gearp** [comment]
@chenkie a similar problem here but mine is actually trying to retrieve the file from https://cdn.eu.auth0.com. 
However for some reason I get the same 403 for the file. It was working before but I couldn't figure out anything that I could have changed to break the app. 

I'm  running a cordova/angular app using the url http://localhost:3000 
and my client settings at Auth0 has http://localhost:3000/* in the Allowed Origins.

I'm using auth0.min.js v8.5.0 and lock v10.13.0

Any idea ?
Thanks

**Comment by gearp** [comment]
@AlexanderKozhevin did you find out the problem ?

**Comment by gearp** [comment]
Got it to work. I've mistakenly used the wrong clientId in my app. When I deleted the old client my app stop working. Then I set the right one and everything worked again.
