### ISSUE TITLE
authorization_error event fires on success

### ISSUE THREAD

**Issue by neeler** [auth0/angular-lock#22]
Not a big deal, but slightly annoying.

Using this stack:
https://cdn.auth0.com/js/auth0/8.0.0/auth0.min.js
http://cdn.auth0.com/js/lock/10.10.0/lock.min.js
angular-lock ( npm version: 2.0.0-beta.0 )

**Comment by chenkie** [comment]
What comes back in the error?

**Comment by neeler** [comment]
error is undefined / the event is fired without parameters
