### ISSUE TITLE
Auth0 is not a constructor

### ISSUE THREAD

**Issue by johnnyasantoss** [auth0/angular-lock#23]
There's a problem when using this package with [auth0-lock](https://www.npmjs.com/package/auth0-lock)

I guess that the docs isn't updated.
![[screenshot](http://prnt.sc/e03gmk)](http://image.prntscr.com/image/612a9c0892264ec28080213f3d07cfb1.png)

+info: [StackOverflow](http://stackoverflow.com/questions/41707970/auth0-is-not-a-consutructor-angularjs-and-auth0/41763628)

**Comment by chenkie** [comment]
Looks like you're using Lock v10.9 or higher with angular-lock v1. Please use angular-lock v2 as stated in the readme.

```bash
npm intsall angular-lock@2.0.0-beta.1
```

or

```
bower install angular-lock#2.0.0-beta.1
```

**Comment by johnnyasantoss** [comment]
Thanks, I found this answer later after creating this issue, sorry!

Is there any milestone to get compatibility between this versions?

**Comment by chenkie** [comment]
No prob.

The full release should be along shortly. Likely end of week or early next 👍
