### ISSUE TITLE
webAuth.renewAuth not exposed in angular-lock

### ISSUE THREAD

**Issue by aaaa0441** [auth0/angular-lock#26]
According to https://auth0.com/docs/api-auth/tutorials/silent-authentication, for refreshing an expired token (which is one way for silent authentication?) in an SPA, the `renewAuth` method needs to be called.

angular-lock currently does not expose this method form auth0.WebAuth. Is there any concern not doing so?

**Comment by chenkie** [comment]
There's actually a dedicated library which wraps Auth0.js, which is where you'll find rewewAuth: https://github.com/auth0/angular-auth0

Note that you'll want the v2 branch.

**Comment by aaaa0441** [comment]
Thanks a lot, @chenkie! That works very well. :D I didn't notice 'angular-auth0' project and thought I had to monkey-patch in this lib.
