### ISSUE TITLE
`interceptHash` broken when `html5Mode(true)` & `hashPrefix('')`

### ISSUE THREAD

**Issue by aaaa0441** [auth0/angular-lock#29]
## Installed Versions

* angularjs: `1.6.2`
* auth0.js: `8.9.2`
* auth0-lock: `10.21.1`
* angular-lock: `2.0.3`
* angular-ui-router: `1.0.0-rc.1`

## Symptom

In Angularjs config phase, `$locationProvider.html5Mode(true); $locationProvider.hashPrefix('');` enables HTML5 mode & avoids any hashPrefix.

In `app.run` method, `lock.interceptHash()` is called in order to determine whether user came back from Auth0 authentication with `lock.on('authenticated', callback)` && `lock.on('authorization_error', authErrorHandler)`. However, these event would never be fired.

## Cause

The code change that introduced the issue is PR #27 ([file](https://github.com/auth0/angular-lock/commit/4dcbfa72f136f8311c45c082f87ebccd13cc8b4a#diff-d803e073edf3cce610a6d790f10d41c7L89)). It is ok to replace `window.location.hash` with `$location.hash()`. But removing the `'#' + location.replace(/http.?:\/\/[^/]+/, '').slice(1)` caused above issue symptom because htmlt5mode & ui-router would have already removed the `#` hash before `app.run` is invoked.

**Comment by fabioel** [comment]
I am having the same issue.
The callback is never called
Did you find a solution?

**Comment by aaaa0441** [comment]
Hi @fabioel, I forked the repo and added a commit to avoid the issue: https://github.com/skiddoo/angular-lock/tree/skiddoo
