### ISSUE TITLE
Latest release (2.0.3) compatibility with Lock v11

### ISSUE THREAD

**Issue by sampsonjoliver** [auth0/angular-lock#35]
I'm trying to upgrade our angular app to Lock v11 and auth0.js v9. The latest angular-lock release specifies its dependencies as

```
"dependencies": {
    "angular": "*",
    "auth0-lock": ">=10.13.0",
    "auth0.js": "^8.4.0"
  }
```

I can see in the repo that these have been updated to v11 and v9, but there has been no published released since July of last year.

**Comment by bosticka** [comment]
I am in the same boat.  Why not push a release?  It takes 5 seconds...

**Comment by joshcanhelp** [comment]
https://github.com/auth0/angular-lock/releases/tag/3.0.0
