### ISSUE TITLE
Published version on bower is showing '2.0.3' version number instead of '3.0.0'

### ISSUE THREAD

**Issue by parham-fazel** [auth0/angular-lock#37]
If you look at the tag version 3.0.0 it has the same issue versions on package.json and bower.json are not aligned properly and it seems this is what is published through bower as well.
we still have legacy project with bower in place. Please fix this issue.

**Comment by reederz** [comment]
`bower install angular-lock` gives me 2.0.3 as well. Even if I try to force 3.0.0 .

**Comment by luisrudge** [comment]
Please try with v3.0.1. I just synced the bower/github release.

**Comment by reederz** [comment]
Works perfectly, thank you!
