### ISSUE TITLE
rendering issue with safari mobile

### ISSUE THREAD

**Issue by luisrudge** [auth0/angular-lock#38]
related:
- https://github.com/auth0/lock/issues/1362
- https://github.com/auth0/lock/issues/1357

Can also reproduce with default sample: https://github.com/auth0-samples/auth0-angularjs-samples/tree/embedded-login/01-Embedded-Login

Removing the bootstrap and custom css didn't fix the issue

**Comment by vladys-k** [comment]
Try to use in the HTML <head> tag or within CSS
<style>
 .auth0-lock-container {
     height: 90vh !important;
 }
</style>
