### ISSUE TITLE
Throw Error in Asynchronous Call

### ISSUE THREAD

**Issue by ZZhaoTireless** [auth0/angular-lock#39]
Hi, when I am using angular-lock in an asynchronous call, it keeps to throw me an error of 

```
angular.min.js:124 Error: A `clientID` string must be provided as first argument.
    at e (lock.min.js:9)
    at new e (lock.min.js:9)
    at t.$get (angular-lock.min.js:1)
    at Object.invoke (angular.min.js:44)
    at angular.min.js:46
    at d (angular.min.js:43)
    at e (angular.min.js:44)
    at Object.invoke (angular.min.js:44)
    at O.instance (angular.min.js:95)
    at p (angular.min.js:69)
(anonymous) @ angular.min.js:124
```

And  my code is 

```
angular.element(document).ready(function() {
        $http.get('<url>').then(function(response) {
            angular.module('authApp')
                .config(function(lockProvider) {
                    var lockOptions = {...}
                    lockProvider.init({
                        domain: response.data.auth0.domain,
                        clientID: response.data.auth0.clientId,
                        options: lockOptions
                    });
            });

            angular.bootstrap(document, ['authApp']);
        }, function(err) {
            console.error('Error loading the application environment.', err);
        });
    });
```

My application doesn't break but I am asked to eliminate the error. Is there any way I could change to avoid this error, thanks!

**Comment by luisrudge** [comment]
are you sure `response.data.auth0.clientId` (notice the `clientID` and `clientId` difference) is being defined in the response? That's the only way this call might fail.

**Comment by SalmanCse** [comment]
Error: A `clientID` string must be provided as first argument.
▼ 2 stack frames were expanded.
Auth0Lock.Base
node_modules/auth0-lock/lib/core.js:57
new Auth0Lock
node_modules/auth0-lock/lib/index.js:49
▲ 2 stack frames were expanded.
new LoginAuth0
http://localhost:3000/static/js/bundle.js:91366:19
  91363 |     _this._lock.show();
  91364 |   };
  91365 | 
> 91366 |   _this._lock = new __WEBPACK_IMPORTED_MODULE_1_auth0_lock___default.a(Object({"NODE_ENV":"development","PUBLIC_URL":""}).REACT_APP_AUTH_0_CLIENT_ID, Object({"NODE_ENV":"development","PUBLIC_URL":""}).REACT_APP_AUTH_0_DOMAIN);
        |                 ^  91367 | 
  91368 |   return _this;
  91369 | }
View source

what is problem ??luisrudge
