### ISSUE TITLE
Custom OAuth Connection ... unsuccessful

### ISSUE THREAD

**Issue by wendelicious** [auth0/angular-lock#8]
I need a single auth provider: a custom OAuth provider (Infusionsoft ID).  Currently, my auth0 account is `dietsoda`.

By way of background:
- I created the custom connection, and it seems to be toggled in the extensions
- Clicking "test" seems to log me into the custom (Infusionsoft) OAuth provider
- I'm starting with the demo project provided for Angular 1.x.  Nothing more.
- I need exactly that single provider

I've seen a few things that may or may not be related.  
- `show( { connections: ['InfusionsoftID-CAS-Test']} )` doesn't show any buttons at all, but `show( { connections: ['InfusionsoftID-CAS-Test', 'google-oauth2']} )` shows both.
- Verified here: http://jsfiddle.net/uen4r283/1/
- There doesn't seem to be an angular equivalent of: https://auth0.com/docs/libraries/lock/v9/ui-customization#adding-a-new-ui-element-using-javascript (without JQuery, how do I select?)
- I've read documentation that `show()` requires `allowedConnections` but `connections` seems to actually modify the set of buttons available
- I can't seem to find the correct set of options to configure the custom button programmatically using the `lockProvider`

**Comment by chenkie** [comment]
It looks like you're on a pretty old version of Lock in that fiddle. Can you try with v10.4?

**Comment by Quantas** [comment]
I am having this exact same issue/use-case. Using angular-lock 1.0.3...

I tried modifying the fiddle too, and still get the same results on 10.4.

**Comment by chenkie** [comment]
This issue comes from Lock itself--the feature was missing from there. Should be out next week :)
